env:
  IMAGE_NAME: basic-flask

steps:
  - key: build
    label: ":docker: Build container image"
    commands:
      - "docker build python -t $$IMAGE_NAME"

  - label: ":test_tube: Test"
    command: "echo 'mock test the container image'"
    key: test
    depends_on: build

  - label: ":mag: Scan container image with Syft"
    commands:
      - "syft scan $$IMAGE_NAME -o spdx-json=$$IMAGE_NAME-sbom.json"
    artifact_paths:
      - "basic-flask-sbom.json"
    depends_on: build

  - label: ":hammer: Build AWS Nitro Enclaves Image File (EIF)"
    commands:
      - "anjuna-nitro-cli build-enclave --docker-uri $$IMAGE_NAME --output-file $$IMAGE_NAME.eif"
    depends_on: build
