steps:
  - label: ":hammer: Build Python"
    commands:
      - "docker build python -t basic-flask"
      - "curl -sSfL https://raw.githubusercontent.com/docker/sbom-cli-plugin/main/install.sh | sh -s --"
      - "docker version"
      - "docker info"
      - "pwd"
      - "docker sbom basic-flask --format spdx-json --output basic-flask-sbom.json"
    artifact_paths:
      - "basic-flask-sbom.json"
    key: build

  - label: ":test_tube: Test"
    command: "echo 'mock test'"
    key: test
    depends_on: build
