env:
  IMAGE_NAME: basic-flask

steps:
  - label: ":hammer: Build Docker image"
    commands:
      - "docker build python -t $$IMAGE_NAME"

  - label: "Scan Docker image with Syft"
    commands:
      - "syft scan $$IMAGE_NAME -o spdx-json=$$IMAGE_NAME-sbom.json"
    artifact_paths:
      - "basic-flask-sbom.json"
    key: build

  - label: "Build AWS Nitro Enclaves Image File (EIF)"
    commands:
      - "anjuna-nitro-cli build-enclave --docker-uri $$IMAGE_NAME --output-file $$IMAGE_NAME.eif"

  - label: ":test_tube: Test"
    command: "echo 'mock test'"
    key: test
    depends_on: build
